remote_theme: chrisrhymes/bulma-clean-theme

title: COVID-19 Malta
tagline: COVID-19 Malta
email: claude@bajada.info
description: >
  An educational site providing data and information about the novel Coronavirus

url: "https://covid-malta.github.io/"


google_analytics: UA-162566521-1

author: Claude Bajada
